version: "1.0"
info:
  model: int-scaffold
packages:
- name: COMPTESProject
  gitServerName: myGit
  gitUrl: https://github.com/cgodartSlagsoa
  gitUsername: cgodartSlagsoa
  gitBranch: main
- name: MA_COMMUN
  gitServerName: myGit
  gitUrl: https://github.com/cgodartSlagsoa
  gitUsername: cgodartSlagsoa
  gitBranch: main
services:
- serviceName: project.comptes.integrations:manageComptesIn
  packages:
  - name: COMPTESProject
    version: "1.0"
